project:
  type: website
  output-dir: docs


website:
  title: "Practice Website For BNS3"
  navbar:
    background: "#702b84"
    left:
      - href: index.qmd
        text: Home
      - text: Demographics
        menu:
          - href: Practice.qmd
            text: Personal Demographics

format:
  html:
    theme: 
      - cosmo
      - styles.css
    toc: true
    toc_float: yes